/**
 * Centralized Numerical Tolerances
 * Derived strictly from NUMERICAL_POLICY.md per ADR-009.
 * Do not introduce arbitrary tolerance definitions elsewhere.
 */

export const NUMERICAL_TOLERANCES = {
  ZERO_TOLERANCE: 1e-7,
  ORTHOGONALITY_TOLERANCE: 1e-6,
  RANK_TOLERANCE: 1e-6,
  SINGULAR_VALUE_TOLERANCE: 1e-6,
} as const;

export const ZERO_TOLERANCE = NUMERICAL_TOLERANCES.ZERO_TOLERANCE;
export const ORTHOGONALITY_TOLERANCE = NUMERICAL_TOLERANCES.ORTHOGONALITY_TOLERANCE;
export const RANK_TOLERANCE = NUMERICAL_TOLERANCES.RANK_TOLERANCE;
export const SINGULAR_VALUE_TOLERANCE = NUMERICAL_TOLERANCES.SINGULAR_VALUE_TOLERANCE;
