import type { Module } from "@/features/curriculum/types";

export const module4: Module = {
  id: "module-4",
  slug: "linear-transformations",
  title: "Linear Transformations",
  order: 4,
  estimatedHours: 10,
  description:
    "Study maps between vector spaces that preserve addition and scaling: kernels, images, the Rank-Nullity Theorem, matrix representations, and change of basis.",
  learningObjectives: [
    "Define linear transformations and verify linearity conditions T(u + v) = T(u) + T(v) and T(cv) = cT(v).",
    "Compute and visualize kernel (null space) and image (range).",
    "Master the Rank-Nullity Theorem: dim(Ker T) + dim(Im T) = dim(V).",
    "Construct matrix representations under standard and non-standard bases.",
    "Perform change of basis transformations and study the vector space of linear mappings L(V, W).",
  ],
  topics: [
    {
      id: "mod4-linear-transformations",
      moduleId: "module-4",
      slug: "linear-transformations",
      title: "Linear Transformations",
      order: 1,
      status: "published",
      difficulty: "introductory",
      estimatedMinutes: 20,
      description: "Understand functions between vector spaces that preserve vector addition and scalar multiplication, transforming grids and coordinate lines uniformly.",
      learningObjectives: [
        "Test functions for linearity.",
        "Visualize linear transformations as grid deformations where origin stays fixed and parallel grid lines remain parallel and evenly spaced.",
      ],
      prerequisites: [],
      visualizationTypes: ["linear-transformation", "matrix-transformation"],
      sections: [
        {
          id: "sec-why",
          title: "Why This Matters",
          type: "why-it-matters",
          content: "Linear transformations are the fundamental operations of linear algebra, modeling rotations, reflections, projections, shears, and scalings in geometry and physics.",
        },
        {
          id: "sec-def",
          title: "Definition of Linearity",
          type: "definition",
          content: "A mapping T: V -> W between vector spaces is linear if for all u, v in V and scalars c in F: T(u + v) = T(u) + T(v) and T(c u) = c T(u).",
          formula: "T(c\\mathbf{u} + \\mathbf{v}) = cT(\\mathbf{u}) + T(\\mathbf{v})",
        },
      ],
      examples: [],
      exercises: [],
      visualizationPresets: [
        {
          presetId: "linear-transformation-2d",
          title: "2D Grid Transformation",
          dimension: 2,
          type: "linear-transformation",
        },
      ],
      relatedTopics: ["mod4-kernels-and-images", "mod4-matrix-representation"],
    },
    {
      id: "mod4-kernels-and-images",
      moduleId: "module-4",
      slug: "kernels-and-images",
      title: "Kernels and Images",
      order: 2,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 25,
      description: "Analyze the kernel (vectors mapped to zero) and image (all possible outputs) of a linear transformation.",
      learningObjectives: [
        "Compute the kernel Ker(T) and image Im(T).",
        "Prove that Ker(T) is a subspace of domain V and Im(T) is a subspace of codomain W.",
      ],
      prerequisites: ["mod4-linear-transformations"],
      visualizationTypes: ["linear-transformation", "subspace"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod4-rank-nullity-theorem"],
    },
    {
      id: "mod4-rank-nullity-theorem",
      moduleId: "module-4",
      slug: "rank-nullity-theorem",
      title: "Rank-Nullity Theorem",
      order: 3,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 25,
      description: "The conservation of dimension in linear mapping: the dimension of the domain equals the nullity plus the rank.",
      learningObjectives: [
        "State and prove the Rank-Nullity Theorem: dim(Ker T) + dim(Im T) = dim(V).",
        "Visualize dimension mapping between domain and codomain spaces.",
      ],
      prerequisites: ["mod4-kernels-and-images"],
      visualizationTypes: ["linear-transformation", "subspace"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod4-matrix-representation"],
    },
    {
      id: "mod4-matrix-representation",
      moduleId: "module-4",
      slug: "matrix-representation-of-a-linear-transformation",
      title: "Matrix Representation of a Linear Transformation",
      order: 4,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 25,
      description: "Convert any abstract linear transformation between finite-dimensional spaces into a concrete matrix by tracking the images of basis vectors.",
      learningObjectives: [
        "Construct matrix [T]_{B,C} relative to ordered domain basis B and codomain basis C.",
        "Compute T(v) using matrix-vector multiplication [T(v)]_C = [T]_{B,C} [v]_B.",
      ],
      prerequisites: ["mod4-linear-transformations"],
      visualizationTypes: ["matrix-transformation", "basis"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod4-change-of-basis"],
    },
    {
      id: "mod4-change-of-basis",
      moduleId: "module-4",
      slug: "change-of-basis",
      title: "Change of Basis",
      order: 5,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 25,
      description: "Translate vector coordinates and transformation matrices between different coordinate frames using transition matrices P_{C <- B}.",
      learningObjectives: [
        "Calculate the change-of-basis transition matrix P_{C <- B}.",
        "Transform linear operators under new bases: [T]_C = P^{-1} [T]_B P.",
      ],
      prerequisites: ["mod4-matrix-representation"],
      visualizationTypes: ["basis", "matrix-transformation"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod4-linear-space-of-linear-mappings"],
    },
    {
      id: "mod4-linear-space-of-linear-mappings",
      moduleId: "module-4",
      slug: "linear-space-of-linear-mappings",
      title: "Linear Space of Linear Mappings",
      order: 6,
      status: "published",
      difficulty: "advanced",
      estimatedMinutes: 20,
      description: "Recognize that the set of all linear transformations L(V, W) itself forms a vector space isomorphic to M_{m x n}(F).",
      learningObjectives: [
        "Verify vector space properties for L(V, W) under function addition and scalar scaling.",
        "Demonstrate the isomorphism between L(V, W) and m x n matrices.",
      ],
      prerequisites: ["mod4-change-of-basis"],
      visualizationTypes: ["subspace"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod4-change-of-basis"],
    },
  ],
};
