import type { Module } from "@/features/curriculum/types";

export const module3: Module = {
  id: "module-3",
  slug: "inner-product-spaces",
  title: "Inner Product Spaces",
  order: 3,
  estimatedHours: 10,
  description:
    "Equip vector spaces with geometry: lengths, angles, orthogonality, projections, Gram-Schmidt orthogonalization, least squares, and QR decomposition.",
  learningObjectives: [
    "Define inner products and induce vector norms and metrics.",
    "Understand orthogonality, perpendicularity, and orthogonal complements.",
    "Compute and visualize orthogonal projections onto lines, planes, and general subspaces.",
    "Perform Gram-Schmidt orthogonalization and QR factorizations.",
    "Solve overdetermined linear systems via least-squares projections.",
  ],
  topics: [
    {
      id: "mod3-inner-product-spaces",
      moduleId: "module-3",
      slug: "inner-product-spaces",
      title: "Inner Product Spaces",
      order: 1,
      status: "published",
      difficulty: "introductory",
      estimatedMinutes: 20,
      description: "Generalize the dot product to abstract inner product axioms (positivity, linearity, conjugate symmetry) for general vector spaces.",
      learningObjectives: ["Verify inner product axioms for weighted dot products and integral inner products on function spaces."],
      prerequisites: [],
      visualizationTypes: ["vectors"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-norms"],
    },
    {
      id: "mod3-norms",
      moduleId: "module-3",
      slug: "norms",
      title: "Norms",
      order: 2,
      status: "published",
      difficulty: "introductory",
      estimatedMinutes: 15,
      description: "Measure vector lengths, distances, and prove the fundamental Cauchy-Schwarz and Triangle Inequalities.",
      learningObjectives: [
        "Compute Euclidean and general induced norms ||v|| = sqrt(⟨v,v⟩).",
        "Apply Cauchy-Schwarz inequality |⟨u,v⟩| <= ||u|| ||v||.",
      ],
      prerequisites: ["mod3-inner-product-spaces"],
      visualizationTypes: ["vectors"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-orthogonality"],
    },
    {
      id: "mod3-orthogonality",
      moduleId: "module-3",
      slug: "orthogonality",
      title: "Orthogonality",
      order: 3,
      status: "published",
      difficulty: "introductory",
      estimatedMinutes: 20,
      description: "Characterize perpendicular vectors where ⟨u,v⟩ = 0 and prove the generalized Pythagorean Theorem in inner product spaces.",
      learningObjectives: ["Test for orthogonality and orthonormal vector sets."],
      prerequisites: ["mod3-norms"],
      visualizationTypes: ["vectors"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-projections-and-subspaces"],
    },
    {
      id: "mod3-projections-and-subspaces",
      moduleId: "module-3",
      slug: "projections-and-subspaces",
      title: "Projections and Subspaces",
      order: 4,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 25,
      description: "Project vectors onto 1D lines and multi-dimensional subspaces, minimizing the perpendicular distance error vector.",
      learningObjectives: [
        "Derive the scalar and vector projection formulas.",
        "Visualize projection as the closest point in a subspace to an external vector.",
      ],
      prerequisites: ["mod3-orthogonality"],
      visualizationTypes: ["projection", "subspace"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-orthogonal-projections"],
    },
    {
      id: "mod3-orthogonal-complementary-subspaces",
      moduleId: "module-3",
      slug: "orthogonal-complementary-subspaces",
      title: "Orthogonal Complementary Subspaces",
      order: 5,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 20,
      description: "Explore the orthogonal complement W^⊥ of a subspace W and prove the fundamental decomposition V = W ⊕ W^⊥.",
      learningObjectives: [
        "Compute the orthogonal complement of column and null spaces.",
        "Verify dim(W) + dim(W^⊥) = dim(V).",
      ],
      prerequisites: ["mod3-projections-and-subspaces"],
      visualizationTypes: ["orthogonal-complement", "plane", "line"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-orthogonal-projections"],
    },
    {
      id: "mod3-orthogonal-projections",
      moduleId: "module-3",
      slug: "orthogonal-projections",
      title: "Orthogonal Projections",
      order: 6,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 25,
      description: "Construct projection matrices P = A(AᵀA)⁻¹Aᵀ for arbitrary subspaces and study their idempotent and symmetric properties (P² = P, Pᵀ = P).",
      learningObjectives: [
        "Compute projection matrices onto column spaces.",
        "Demonstrate the Best Approximation Theorem.",
      ],
      prerequisites: ["mod3-orthogonal-complementary-subspaces"],
      visualizationTypes: ["projection", "subspace"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-gram-schmidt-orthogonalization", "mod3-least-squares-approximations"],
    },
    {
      id: "mod3-gram-schmidt-orthogonalization",
      moduleId: "module-3",
      slug: "gram-schmidt-orthogonalization",
      title: "Gram-Schmidt Orthogonalization",
      order: 7,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 30,
      description: "Convert an arbitrary basis into an orthonormal basis by sequentially subtracting orthogonal projection components.",
      learningObjectives: [
        "Execute the classical and modified Gram-Schmidt algorithm step by step.",
        "Animate the geometric subtraction of vector projections to produce perpendicular vectors.",
      ],
      prerequisites: ["mod3-orthogonal-projections"],
      visualizationTypes: ["qr-decomposition", "vectors", "projection"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-qr-decomposition"],
    },
    {
      id: "mod3-least-squares-approximations",
      moduleId: "module-3",
      slug: "least-squares-approximations",
      title: "Least Squares Approximations",
      order: 8,
      status: "published",
      difficulty: "advanced",
      estimatedMinutes: 30,
      description: "Find the best fit solution x̂ to inconsistent linear systems Ax = b by solving the normal equations AᵀAx̂ = Aᵀb.",
      learningObjectives: [
        "Formulate and solve normal equations for linear regression and surface fitting.",
        "Interpret least squares geometrically as projecting b onto the column space Col(A).",
      ],
      prerequisites: ["mod3-orthogonal-projections"],
      visualizationTypes: ["least-squares", "projection"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-qr-decomposition"],
    },
    {
      id: "mod3-qr-decomposition",
      moduleId: "module-3",
      slug: "qr-decomposition",
      title: "QR Decomposition",
      order: 9,
      status: "published",
      difficulty: "advanced",
      estimatedMinutes: 25,
      description: "Factor a matrix A = QR into an orthogonal matrix Q and an upper-triangular matrix R for numerically stable linear solves.",
      learningObjectives: [
        "Relate Gram-Schmidt steps directly to the upper-triangular matrix R.",
        "Solve least-squares problems via Rx̂ = Qᵀb.",
      ],
      prerequisites: ["mod3-gram-schmidt-orthogonalization", "mod3-least-squares-approximations"],
      visualizationTypes: ["qr-decomposition", "basis"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod3-gram-schmidt-orthogonalization"],
    },
  ],
};
