import type { Module } from "@/features/curriculum/types";

export const module1: Module = {
  id: "module-1",
  slug: "matrices-eigenvalues-decompositions",
  title: "Matrices, Eigenvalues and Decompositions",
  order: 1,
  estimatedHours: 10,
  description:
    "Explore matrix operations, characteristic equations, eigenvalues, eigenvectors, diagonalization, symmetric matrices, SVD, and pseudoinverses with intuitive geometric visualizations.",
  learningObjectives: [
    "Compute and interpret characteristic polynomials and eigenvalues.",
    "Visualize eigenvectors as invariant directions under matrix transformations.",
    "Understand matrix diagonalization and change of basis.",
    "Explore the geometry of symmetric and positive definite matrices.",
    "Master Singular Value Decomposition (SVD) and its geometric interpretation.",
  ],
  topics: [
    {
      id: "mod1-characteristic-equations",
      moduleId: "module-1",
      slug: "characteristic-equations",
      title: "Characteristic Equations",
      order: 1,
      status: "published",
      difficulty: "introductory",
      estimatedMinutes: 20,
      description: "Understand det(A - λI) = 0 and how the roots of the characteristic polynomial determine the eigenvalues of a linear transformation.",
      learningObjectives: [
        "Formulate the characteristic equation det(A - λI) = 0.",
        "Calculate the characteristic polynomial for 2x2 and 3x3 matrices.",
        "Determine the algebraic multiplicity of eigenvalues.",
      ],
      prerequisites: [],
      visualizationTypes: ["matrix-transformation"],
      sections: [
        {
          id: "sec-why",
          title: "Why This Matters",
          type: "why-it-matters",
          content: "Finding directions where a matrix acts merely by scaling is fundamental across quantum mechanics, computer graphics, data compression, and stability analysis.",
        },
        {
          id: "sec-def",
          title: "Mathematical Definition",
          type: "definition",
          content: "For a square matrix A, a scalar λ is an eigenvalue if there exists a non-zero vector v such that Av = λv. This is equivalent to (A - λI)v = 0 having non-trivial solutions, which occurs if and only if det(A - λI) = 0.",
          formula: "\\det(A - \\lambda I) = 0",
        },
      ],
      examples: [],
      exercises: [],
      visualizationPresets: [
        {
          presetId: "characteristic-polynomial-2d",
          title: "Matrix Scaling Transformation",
          dimension: 2,
          type: "matrix-transformation",
        },
      ],
      relatedTopics: ["mod1-eigenvalues-eigenvectors"],
    },
    {
      id: "mod1-eigenvalues-eigenvectors",
      moduleId: "module-1",
      slug: "eigenvalues-eigenvectors",
      title: "Eigenvalues and Eigenvectors",
      order: 2,
      status: "published",
      difficulty: "introductory",
      estimatedMinutes: 25,
      description: "Discover vectors that do not change direction when transformed by a matrix, only scaled by their corresponding eigenvalue.",
      learningObjectives: [
        "Identify invariant directions geometrically under linear transformations.",
        "Solve for eigenvectors corresponding to known eigenvalues.",
        "Distinguish algebraic multiplicity from geometric multiplicity.",
      ],
      prerequisites: ["mod1-characteristic-equations"],
      visualizationTypes: ["eigenvectors", "matrix-transformation"],
      sections: [
        {
          id: "sec-intuition",
          title: "Geometric Intuition",
          type: "intuition",
          content: "When a matrix transforms space, most vectors get rotated and stretched. Eigenvectors are the special vectors whose direction is completely preserved—they simply stretch, shrink, or flip along their original line.",
        },
        {
          id: "sec-formula",
          title: "The Eigenvalue Equation",
          type: "formal-math",
          content: "The defining relationship Av = λv connects matrix multiplication directly to scalar scaling for specific invariant directions.",
          formula: "A \\mathbf{v} = \\lambda \\mathbf{v}",
        },
      ],
      examples: [],
      exercises: [],
      visualizationPresets: [
        {
          presetId: "eigenvector-2d",
          title: "2D Invariant Directions",
          dimension: 2,
          type: "eigenvectors",
        },
      ],
      relatedTopics: ["mod1-diagonalization", "mod1-characteristic-equations"],
    },
    {
      id: "mod1-diagonalization",
      moduleId: "module-1",
      slug: "diagonalization",
      title: "Diagonalization",
      order: 3,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 25,
      description: "Factor a matrix into A = PDP⁻¹ to decouple coupled linear transformations into independent coordinate scalings.",
      learningObjectives: [
        "Construct the modal matrix P and diagonal matrix D.",
        "Determine the criteria for matrix diagonalizability.",
        "Apply diagonalization to compute matrix powers A^k efficiently.",
      ],
      prerequisites: ["mod1-eigenvalues-eigenvectors"],
      visualizationTypes: ["diagonalization", "basis"],
      sections: [
        {
          id: "sec-def",
          title: "Diagonalization Form",
          type: "definition",
          content: "An n x n matrix A is diagonalizable if it is similar to a diagonal matrix D, meaning there exists an invertible matrix P whose columns are eigenvectors of A such that A = P D P⁻¹.",
          formula: "A = P D P^{-1}",
        },
      ],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod1-similar-matrices", "mod1-eigenvalues-eigenvectors"],
    },
    {
      id: "mod1-differential-equations",
      moduleId: "module-1",
      slug: "applications-to-differential-equations",
      title: "Applications to Differential Equations",
      order: 4,
      status: "published",
      difficulty: "advanced",
      estimatedMinutes: 30,
      description: "Solve systems of linear first-order differential equations x' = Ax using eigenbases and phase portrait trajectories.",
      learningObjectives: [
        "Convert systems of differential equations into matrix form x' = Ax.",
        "Solve decoupled systems using matrix exponentials and eigenvalues.",
        "Analyze stability and phase portraits geometrically.",
      ],
      prerequisites: ["mod1-diagonalization"],
      visualizationTypes: ["trajectory"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod1-diagonalization"],
    },
    {
      id: "mod1-symmetric-matrices",
      moduleId: "module-1",
      slug: "symmetric-matrices",
      title: "Symmetric Matrices",
      order: 5,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 20,
      description: "Explore the spectral theorem for real symmetric matrices: real eigenvalues and mutually orthogonal eigenvectors.",
      learningObjectives: [
        "State and apply the Spectral Theorem for symmetric matrices.",
        "Construct orthogonal diagonalization A = Q D Qᵀ.",
      ],
      prerequisites: ["mod1-diagonalization"],
      visualizationTypes: ["eigenvectors"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod1-positive-definite-matrices"],
    },
    {
      id: "mod1-positive-definite-matrices",
      moduleId: "module-1",
      slug: "positive-definite-matrices",
      title: "Positive Definite Matrices",
      order: 6,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 20,
      description: "Study quadratic forms xᵀAx > 0 and energy landscapes where symmetric matrices define bowl-shaped quadratic surfaces.",
      learningObjectives: [
        "Test for positive definiteness via eigenvalues, pivots, and Sylvester's criterion.",
        "Visualize quadratic surfaces xᵀAx = 1 as ellipsoids.",
      ],
      prerequisites: ["mod1-symmetric-matrices"],
      visualizationTypes: ["surface", "ellipsoid"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod1-symmetric-matrices", "mod1-singular-value-decomposition"],
    },
    {
      id: "mod1-similar-matrices",
      moduleId: "module-1",
      slug: "similar-matrices",
      title: "Similar Matrices",
      order: 7,
      status: "published",
      difficulty: "intermediate",
      estimatedMinutes: 20,
      description: "Understand similarity transformations B = P⁻¹AP as representing the exact same linear transformation under different coordinate bases.",
      learningObjectives: [
        "Define matrix similarity and identify preserved invariants (trace, determinant, eigenvalues).",
        "Interpret similarity geometrically as coordinate system translation.",
      ],
      prerequisites: ["mod1-diagonalization"],
      visualizationTypes: ["basis", "matrix-transformation"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod1-diagonalization"],
    },
    {
      id: "mod1-singular-value-decomposition",
      moduleId: "module-1",
      slug: "singular-value-decomposition",
      title: "Singular Value Decomposition",
      order: 8,
      status: "published",
      difficulty: "advanced",
      estimatedMinutes: 35,
      description: "The crown jewel of linear algebra: factor any rectangular matrix into rotation, scaling, and rotation (A = UΣVᵀ).",
      learningObjectives: [
        "Understand the geometric action of SVD transforming a unit sphere into a hyper-ellipsoid.",
        "Calculate singular values and singular vectors for rectangular matrices.",
        "Apply SVD to low-rank approximations and data compression.",
      ],
      prerequisites: ["mod1-positive-definite-matrices", "mod1-symmetric-matrices"],
      visualizationTypes: ["svd", "unit-sphere", "ellipsoid"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod1-generalized-inverses"],
    },
    {
      id: "mod1-generalized-inverses",
      moduleId: "module-1",
      slug: "generalized-inverses",
      title: "Generalized Inverses",
      order: 9,
      status: "published",
      difficulty: "advanced",
      estimatedMinutes: 25,
      description: "Construct the Moore-Penrose pseudoinverse A⁺ to find optimal minimum-norm solutions to rectangular and rank-deficient systems.",
      learningObjectives: [
        "Define the Moore-Penrose pseudoinverse via SVD: A⁺ = V Σ⁺ Uᵀ.",
        "Compute least-squares and minimum-norm solutions geometrically.",
      ],
      prerequisites: ["mod1-singular-value-decomposition"],
      visualizationTypes: ["projection", "least-squares"],
      sections: [],
      examples: [],
      exercises: [],
      visualizationPresets: [],
      relatedTopics: ["mod1-singular-value-decomposition"],
    },
  ],
};
